// ═══════════════════════════════════════════════════════════════════
// Constants - Crop Data & Fertilizer Information
// Based on ICAR (Indian Council of Agricultural Research) standards
// ═══════════════════════════════════════════════════════════════════

const FERTILIZER_PRICES = {
  urea: 25,       // ₹/kg
  dap: 45,        // ₹/kg (Di-Ammonium Phosphate)
  mop: 40         // ₹/kg (Muriate of Potash)
};

const CROPS = {
  rice: {
    name: 'Rice (Paddy)',
    icon: '🌾',
    season: 'Kharif (June–Nov)',
    pH: [5.5, 7.5],
    N: [40, 100],
    P: [20, 60],
    K: [20, 60],
    soilTypes: ['clay', 'loamy', 'any'],
    tempRange: [20, 38],
    rainfall: 'high',
    seedRate: 25,
    seedPricePerKg: 35,
    fertilizer: { urea: 90, dap: 50, mop: 40 },
    duration: '120-150 days',
    yield: '25-35 quintals/acre',
    notes: 'Requires standing water during early growth. Best for irrigated areas.'
  },
  wheat: {
    name: 'Wheat',
    icon: '🌿',
    season: 'Rabi (Nov–Apr)',
    pH: [6.0, 7.5],
    N: [40, 80],
    P: [20, 60],
    K: [20, 50],
    soilTypes: ['loamy', 'clay loam', 'any'],
    tempRange: [12, 25],
    rainfall: 'medium',
    seedRate: 40,
    seedPricePerKg: 30,
    fertilizer: { urea: 80, dap: 60, mop: 30 },
    duration: '100-120 days',
    yield: '18-25 quintals/acre',
    notes: 'Cool weather crop. Ideal in North India during winter.'
  },
  maize: {
    name: 'Maize (Corn)',
    icon: '🌽',
    season: 'Kharif/Rabi',
    pH: [5.8, 7.0],
    N: [50, 120],
    P: [25, 65],
    K: [25, 70],
    soilTypes: ['sandy loam', 'loamy', 'any'],
    tempRange: [21, 35],
    rainfall: 'medium',
    seedRate: 8,
    seedPricePerKg: 80,
    fertilizer: { urea: 100, dap: 65, mop: 50 },
    duration: '90-110 days',
    yield: '20-30 quintals/acre',
    notes: 'Good for intercropping. High market demand.'
  },
  groundnut: {
    name: 'Groundnut',
    icon: '🥜',
    season: 'Kharif (Jun–Oct)',
    pH: [5.5, 7.0],
    N: [15, 40],
    P: [20, 60],
    K: [20, 60],
    soilTypes: ['sandy loam', 'loamy'],
    tempRange: [25, 35],
    rainfall: 'medium',
    seedRate: 60,
    seedPricePerKg: 55,
    fertilizer: { urea: 20, dap: 80, mop: 40 },
    duration: '90-120 days',
    yield: '8-12 quintals/acre',
    notes: 'Nitrogen-fixing legume. Good for low-N soils.'
  },
  cotton: {
    name: 'Cotton',
    icon: '🌸',
    season: 'Kharif (Apr–Nov)',
    pH: [6.0, 8.0],
    N: [60, 120],
    P: [30, 70],
    K: [30, 70],
    soilTypes: ['black cotton', 'clay', 'loamy'],
    tempRange: [25, 40],
    rainfall: 'medium',
    seedRate: 3,
    seedPricePerKg: 800,
    fertilizer: { urea: 110, dap: 75, mop: 55 },
    duration: '150-180 days',
    yield: '8-15 quintals/acre',
    notes: 'High water requirement. Best for black soil regions.'
  },
  sugarcane: {
    name: 'Sugarcane',
    icon: '🎋',
    season: 'Year-round',
    pH: [6.0, 7.5],
    N: [100, 200],
    P: [40, 80],
    K: [60, 100],
    soilTypes: ['loamy', 'clay loam'],
    tempRange: [25, 38],
    rainfall: 'high',
    seedRate: 3000,
    seedPricePerKg: 2,
    fertilizer: { urea: 200, dap: 100, mop: 100 },
    duration: '300-360 days',
    yield: '300-400 quintals/acre',
    notes: 'Long duration crop. High sugar recovery in tropical climate.'
  },
  tomato: {
    name: 'Tomato',
    icon: '🍅',
    season: 'All seasons',
    pH: [6.0, 7.0],
    N: [40, 80],
    P: [30, 60],
    K: [40, 80],
    soilTypes: ['sandy loam', 'loamy'],
    tempRange: [20, 30],
    rainfall: 'low',
    seedRate: 0.2,
    seedPricePerKg: 2000,
    fertilizer: { urea: 80, dap: 60, mop: 60 },
    duration: '70-90 days',
    yield: '80-120 quintals/acre',
    notes: 'High-value vegetable crop. Good market returns.'
  },
  pulses: {
    name: 'Pulses (Moong/Tur)',
    icon: '🫘',
    season: 'Kharif/Rabi',
    pH: [6.0, 7.5],
    N: [10, 30],
    P: [20, 50],
    K: [20, 40],
    soilTypes: ['sandy loam', 'loamy', 'any'],
    tempRange: [20, 30],
    rainfall: 'low',
    seedRate: 12,
    seedPricePerKg: 90,
    fertilizer: { urea: 15, dap: 50, mop: 20 },
    duration: '60-90 days',
    yield: '5-8 quintals/acre',
    notes: 'Nitrogen-fixing. Excellent for soil health improvement.'
  },
  banana: {
    name: 'Banana',
    icon: '🍌',
    season: 'Year-round',
    pH: [6.0, 7.5],
    N: [80, 150],
    P: [40, 80],
    K: [100, 200],
    soilTypes: ['loamy', 'clay loam'],
    tempRange: [25, 38],
    rainfall: 'high',
    seedRate: 450,
    seedPricePerKg: 15,
    fertilizer: { urea: 150, dap: 80, mop: 200 },
    duration: '300-365 days',
    yield: '200-400 quintals/acre',
    notes: 'High potassium requirement. Perennial crop.'
  },
  onion: {
    name: 'Onion',
    icon: '🧅',
    season: 'Rabi (Oct–Mar)',
    pH: [6.0, 7.0],
    N: [50, 80],
    P: [30, 50],
    K: [40, 60],
    soilTypes: ['sandy loam', 'loamy'],
    tempRange: [13, 24],
    rainfall: 'low',
    seedRate: 4,
    seedPricePerKg: 250,
    fertilizer: { urea: 65, dap: 50, mop: 50 },
    duration: '100-120 days',
    yield: '80-120 quintals/acre',
    notes: 'Highly profitable. Good storage crop.'
  }
};

module.exports = { FERTILIZER_PRICES, CROPS };
